name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull data using DVC
        run: |
          dvc pull || echo "⚠️ No DVC remote configured, skipping data pull"

      - name: Run Linter (flake8)
        run: |
          flake8 process_data.py test_process.py

      - name: Run Tests (pytest)
        run: |
          pytest -v

      - name: Build Step
        run: echo "✅ Build successful!"

      - name: Deploy (simulation)
        if: github.ref == 'refs/heads/main'
        run: echo "🚀 Deployment triggered on main branch!"
